### ISSUE TITLE
AttributeError: module 'google.cloud.iot_v1 ' has no attribute 'FieldMask'

### ISSUE THREAD

**Issue by fabltd** [googleapis/python-iot#43]
Hello 

When migrating to V2 what is the syntax for the use of FieldMask it appears to be missing.

**Comment by munkhuushmgl** [comment]
Hello @fabltd I think instruction might be in the following:
https://github.com/googleapis/python-iot/commit/f420fd37441c92f3c9324b1d7278b210e3c5a8bc#diff-f411a5009131db5a6c7242b49ca78488f2d274ef9e5e5f4de9262a42108a5386

Could you provide some example or code snippet used?

**Comment by munkhuushmgl** [comment]
Due to inactivity, Im closing this issue

**Comment by fabltd** [comment]
Hi just seen this reply sample code to follow
